### ISSUE TITLE
anti knife

### ISSUE THREAD

**Issue by swifty-tekno** [diamante0018/PlutoGSC#1]
you can override the damage callback and put this in it then return damage if its not melee

onPlayerDamage(eInflictor, eAttacker, iDamage, iDFlags, sMeansOfDeath, sWeapon, vPoint, vDir, sHitLoc, timeOffset)
{
    attacker = eAttacker;
    victim = self;
    //level endon( "game_ended" ); //using this cause last kill to not count and victims death does not count
    self endon("disconnect");
    if ( sMeansOfDeath == "MOD_MELEE" && getDvarInt( "sv_antiknife") == 1 ) 
    {
        //Do not use callback here

    }
    else
    {
        victim [[level.prevCallbackPlayerDamage]](eInflictor, eAttacker, iDamage, iDFlags, sMeansOfDeath, sWeapon, vPoint, vDir, sHitLoc, timeOffset);

        //print( "Player Damage Logging: eInflictor: " + eInflictor.name + " eAtacker: " + eAttacker.name + " iDamage: " + iDamage + " iDFlags: " + iDFlags + " sMeansOfDeath: " + sMeansOfDeath + " sWeapon: " + sWeapon + " vPoint: " + vPoint, " vDir: " + vDir + " sHitLoc: " + sHitLoc + " timeOffset: " + timeOffset);
    }
}

and put this in init  
	level.prevCallbackPlayerDamage = level.callbackPlayerDamage;
	level.callbackPlayerDamage = ::onPlayerDamage;

**Comment by diamante0018** [comment]
Next time, if you have the full code, you can open a pull request, or you can send me a patch so I can apply it to my repo without me doing anything 😃


[FormatPatches](https://git-scm.com/docs/git-format-patch)
